### PR TITLE
Updated dependency versions and main.css; Adjust config.toml and content/_index.md

### PR DESCRIPTION
**Pull request by tjdwill**
Hi, 

As discussed in #16, I updated all of the dev dependencies to bring them up to date and added the changes proposed by @awinterstein. 

I had no problems with `npm install`, so I don't think there's any breakage. I've pasted the results below:

image

## Odd Behavior 

During testing, I tried to run `zola serve` on the theme directory itself and received a few errors from `/config.toml` and `/content/_index.md`, so I changed those accordingly. Once I got the site to build, however, I noticed that the nav bar was not the same, and the social buttons don't load:

image

Was it always like this? I'm not sure why it works on my site but not when serving the theme directly.

### CODE REVIEW

**Comment by tjdwill** [comment]
Also, I don't know how to do so, but can @awinterstein be added as a co-contributor since the CSS changes were his?

**Comment by cerritus-habitica** [comment]
Thank you for integrating my suggestion! :blush: 

> Also, I don't know how to do so, but can @awinterstein be added as a co-contributor since the CSS changes were his?

As far as I see, you'd only need to add a `Co-authored-by` to the commit message of the corresponding commit: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by awinterstein** [comment]
Thank you for integrating my suggestion! 😊

> Also, I don't know how to do so, but can @awinterstein be added as a co-contributor since the CSS changes were his?

As far as I see, you'd only need to add a Co-authored-by to the commit message of the corresponding commit: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by tjdwill** [comment]
Added as co-author. Thank you for that.

**Comment by tchartron** [comment]
Looks great guys thanks for your contribution !

**Pull request merged**
