### PR TITLE
add support for mastodon

### PR DESCRIPTION
**Pull request by ptillemans**
I added support for Mastodon by twiddling with the SVG provided by https://gist.github.com/SpaceOyster/c3d6d573ec375f91b0c91756ceeeb88d#file-mastodon-icon-html

### CODE REVIEW

**Comment by tchartron** [comment]
Hey, thank you for submitting this PR.

Could you also add README informations and theme.toml config just like [here](https://github.com/tchartron/blow/pull/14/files) please before merging ?

**Comment by ptillemans** [comment]
Ok, give me a sec.

**Comment by ptillemans** [comment]
something like this?

**Comment by tchartron** [comment]
Yes, it looks good thanks for contributing !

**Pull request merged**
